### ISSUE TITLE
deep integration wagtail?

### ISSUE THREAD

**Issue by onno-timmerman** [RealOrangeOne/django-plausible#26]
Your doc page says, but what is meant with "deep" ?

Additionally, django-plausible provides an (optional) deep integration with [Wagtail](https://wagtail.io/),

**Comment by RealOrangeOne** [comment]
See [Usage with Wagtail](https://github.com/RealOrangeOne/django-plausible#usage-with-wagtail) in the README.

In short, rather than passing the domain configuration to the tag through the template, you can configure it in the Wagtail admin, in a way which supports different configuration when running in a [multi-site](https://docs.wagtail.org/en/stable/advanced_topics/multi_site_multi_instance_multi_tenancy.html#multi-site) environment
